CREATE DATABASE TRADUCTOR;

USE TRADUCTOR;

--CREAR TABLAS
CREATE TABLE USUARIOS(
	ID CHAR(9) PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE LENGUAJES(
NOMBRE VARCHAR(20) PRIMARY KEY
);

CREATE TABLE PALABRAS_ESPANNOL(
PALABRA VARCHAR(30) PRIMARY KEY,
POPULARIDAD INT NOT NULL DEFAULT 1
);

CREATE TABLE TRADUCCIONES(
ID INT IDENTITY(1,1) PRIMARY KEY,
SPANISH VARCHAR(30) FOREIGN KEY REFERENCES PALABRAS_ESPANNOL(PALABRA),
LENGUAJE VARCHAR(20) FOREIGN KEY REFERENCES LENGUAJES(NOMBRE),
RESULTADO VARCHAR(20) NOT NULL,
CREADOR CHAR(9) FOREIGN KEY REFERENCES USUARIOS(ID),
FECHA DATE NOT NULL,
);
GO;

--CREAR PROCEDIMIENTOS
----OBTENER IDIOMAS DISPONIBLES.
CREATE PROCEDURE OBTENER_IDIOMAS_DISPONIBLES
AS
SELECT NOMBRE FROM LENGUAJES
GO;

----OBTENER 100 PALABRAS MAS POPULARES
CREATE PROCEDURE TOP_100
AS
SELECT TOP 100 PALABRA FROM PALABRAS_ESPANNOL
ORDER BY POPULARIDAD
GO;

--OBTENER IDIOMA MAS POPULAR
CREATE PROCEDURE IDIOMA_POP
AS
SELECT NOMBRE FROM LENGUAJES
INNER JOIN TRADUCCIONES AS T
ON NOMBRE = (SELECT TOP 1 T.LENGUAJE, COUNT(T.RESULTADO) AS CANTIDAD GROUP BY T.LENGUAJE)
GO;

----OBTENER USUARIO CON MAS TRADUCCIONES
CREATE PROCEDURE USUARIO_MAYOR
AS
SELECT U.NOMBRE, COUNT(T.RESULTADO) AS TRADUCCIONES_TOTALES FROM USUARIOS AS U
INNER JOIN TRADUCCIONES AS T
ON U.ID = T.CREADOR
GROUP BY T.CREADOR
GO;

----